name: Handle Request
on:
  issues:
    types: [opened]
jobs:
  handle-request:
    runs-on: ubuntu-latest
    if: "contains(toJSON(github.event.issue.title), '[build]')"
    steps:
      # Check out code using git
      - uses: actions/checkout@v2

      # Install Node 14
      - uses: actions/setup-node@v1
        with:
          node-version: 15
      # - uses: egordm/gha-yarn-node-cache@v1
      - uses: Jaid/action-npm-install@v1.2.4
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          continue-after-seconds: 180
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config pull.rebase false  # merge (the default strategy)
          git pull
      - name: "Handle issue"
        run: node ./action/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          event_number: ${{ github.event.issue.number }}
      - name: Auto Minify
        uses: nizarmah/auto-minify@master
        with:
          maxdepth: 1
          output: ./dist

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository
      - name: Add changes to Git tracking
        run: git add -A .

      - name: Commit changes
        run:  git diff-index --quiet HEAD || git commit --amend --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
